

CREATE DATABASE [Sales]     ON (NAME = 'Sales', FILENAME = 	'D:\MSSQL\DATA\PRODDATA\Sales.mdf', SIZE = 1024MB, FILEGROWTH = 256MB)LOG ON (NAME = 'Sales_log', FILENAME = 'E:\MSSQL\LOG\PRODLOG\Sales_log.ldf', SIZE = 512MB, FILEGROWTH = 125MB)

