BACKUP DATABASE [AdventureWorks2017] TO  DISK = N'F:\MSSQL\BACKUP\PRODBACKUP\Diffbackup\AdventureWorks2017_11042020_0911' WITH  DIFFERENTIAL , NOFORMAT, NOINIT,  NAME = N'AdventureWorks2017-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, COMPRESSION,  STATS = 10
GO
