
CREATE  database UNIVERSITY_DATABASE

USE UNIVERSITY_DATABASE
CREATE TABLE COURSES (
COURSE_ID INT,
COURSENAME CHAR(30),
COURSE_DURATION  INT

)

INSERT INTO COURSES VALUES (101,'COMPUTERS',180)
INSERT INTO COURSES VALUES(102,'ROBOTICS',180)
INSERT INTO COURSES VALUES(103,'CIVIL',180)
INSERT INTO COURSES VALUES(104,'MECHATRONICS',120)

select * from COURSES where [COURSE_NAME] LIKE 'C%'

select * from COURSES where [COURSE_NAME] LIKE '%S'

select * from COURSES where COURSE_DURATION > 50

select * from COURSES where COURSE_DURATION > 50 OR COURSE_DURATION < 130

select  max(COURSE_DURATION) from COURSES

select * from COURSES where COURSE_DURATION > 120 

select * from COURSES where COURSE_DURATION > 120  and  [COURSE_NAME] LIKE 'C%'