USE [master]
RESTORE DATABASE [ORG] FROM  DISK = N'F:\SQL_BACKUPS_FILES\ORG_20201222.BAK' WITH  FILE = 1,  MOVE N'ORG' TO N'D:\MSSQL\DATA\UATDATA\ORG.mdf',  MOVE N'ORG_log' TO N'E:\MSSQL\LOG\UATLOG\ORG_log.ldf',  NOUNLOAD,  STATS = 5




USE [master]
RESTORE DATABASE [PRACTICE] FROM  DISK = N'F:\SQL_BACKUPS_FILES\PRACTICE_20201222.BAK' WITH  FILE = 1,  MOVE N'PRACTICE' TO N'D:\MSSQL\DATA\UATDATA\PRACTICE.mdf',  MOVE N'PRACTICE_log' TO N'E:\MSSQL\LOG\UATLOG\PRACTICE_log.ldf',  NOUNLOAD,  STATS = 5



USE [master]
RESTORE DATABASE [SacretHeart] FROM  DISK = N'F:\SQL_BACKUPS_FILES\SacretHeart_20201222.BAK' WITH  FILE = 1,  MOVE N'SacretHeart' TO N'D:\MSSQL\DATA\UATDATA\SacretHeart.mdf',  MOVE N'SacretHeart_log' TO N'E:\MSSQL\LOG\UATLOG\SacretHeart_log.ldf',  NOUNLOAD,  STATS = 5

