USE [master]
GO

/****** Object:  Database [Pages]    Script Date: 4/16/2021 10:24:38 PM ******/
CREATE DATABASE [Pages]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pages', FILENAME = N'D:\MSSQL\PRODDATA\Pages.mdf' , SIZE =1000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pages_log', FILENAME = N'E:\MSSQL\PRODLOG\Pages_log.ldf' , SIZE = 1000KB , MAXSIZE =  UNLIMITED, FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pages].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pages] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pages] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pages] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pages] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pages] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pages] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pages] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pages] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pages] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pages] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pages] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pages] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pages] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pages] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pages] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Pages] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pages] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pages] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pages] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pages] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pages] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Pages] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pages] SET RECOVERY FULL 
GO

ALTER DATABASE [Pages] SET  MULTI_USER 
GO

ALTER DATABASE [Pages] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pages] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pages] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pages] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Pages] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pages] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Pages] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Pages] SET  READ_WRITE 
GO





Drop database Pages